### ISSUE TITLE
How to prepare dataset for training my own model.

### ISSUE THREAD

**Issue by riitoku** [liruihui/PU-GAN#14]
Hi, appreciate your excellent work.
I have a 3D point cloud dataset  and I want to train your model on this dataset. Can you tell me how to prepare training data?

**Comment by liruihui** [comment]
You can just use Poisson disk sampling in the Meshlab to sample the points from the meshes as your GT.

You may also use the provided sampling code here [PU-Net](https://github.com/yulequan/PU-Net)
