### ISSUE TITLE
Lots of Compile Errors in grouping. I DON't think the author check the code before releasing it.

### ISSUE THREAD

**Issue by hzxie** [liruihui/PU-GAN#15]
When I compile the `grouping` TF operation, I got the following error:

```
query_ball_point.cpp: In function ‘int main()’:
query_ball_point.cpp:107:60: error: cannot convert ‘const float’ to ‘const float*’ for argument ‘4’ to ‘void query_ball_point_cpu(int, int, int, const float*, int, const float*, const float*, int*)’
     query_ball_point_cpu(b,n,m,radius,nsample,xyz1,xyz2,idx);
                                                            ^
query_ball_point.cu(114): error: argument of type "float" is incompatible with parameter of type "const float *"

1 error detected in the compilation of "/tmp/tmpxft_000021dc_00000000-8_query_ball_point.cpp1.ii".
query_ball_point_block.cu(112): error: argument of type "float" is incompatible with parameter of type "const float *"

1 error detected in the compilation of "/tmp/tmpxft_00002207_00000000-8_query_ball_point_block.cpp1.ii".
query_ball_point_grid.cu(122): error: argument of type "float" is incompatible with parameter of type "const float *"

1 error detected in the compilation of "/tmp/tmpxft_00002211_00000000-8_query_ball_point_grid.cpp1.ii".
gcc: error: query_ball_point_grid_count.cu: No such file or directory
gcc: warning: ‘-x c++’ after last input file has no effect
gcc: fatal error: no input files
compilation terminated.
```

**Comment by hzxie** [comment]
I think you shoud change

```
query_ball_point_cpu(b,n,m,radius,nsample,xyz1,xyz2,idx)
```

to

```
query_ball_point_cpu(b,n,m,&radius,nsample,xyz1,xyz2,idx)
```

**Comment by hzxie** [comment]
Don't you check this code before releasing it?
How do you perform the experiments?

**Comment by hzxie** [comment]
The same problem in `query_ball_point.cu`.
According to your declaration, the variable `radius` is float.

https://github.com/liruihui/PU-GAN/blob/c7add7bbe32991d316375e8aba65e1f87a545763/tf_ops/grouping/query_ball_point.cu#L93

However, you use it as an array.

https://github.com/liruihui/PU-GAN/blob/c7add7bbe32991d316375e8aba65e1f87a545763/tf_ops/grouping/query_ball_point.cu#L37

It should change to:

```
if (d<*radius) {
```

**Comment by hzxie** [comment]
After fixing several issues mentioned above, I got another error:

```
gcc: error: query_ball_point_grid_count.cu: No such file or directory
gcc: warning: ‘-x c++’ after last input file has no effect
gcc: fatal error: no input files
compilation terminated.
```

**Comment by liruihui** [comment]
Sorry to bother you so much. Please check the tf_ops from [pointnet2](https://github.com/charlesq34/pointnet2) and [PU-Net](https://github.com/yulequan/PU-Net) for more details about how to compile them.  I just follow the same configuration as them and I do not get your problem.

Ruihui Li

**Comment by hzxie** [comment]
The same problem in `query_ball_point.cu`.
According to your declaration, the variable `radius` is float.

https://github.com/liruihui/PU-GAN/blob/c7add7bbe32991d316375e8aba65e1f87a545763/tf_ops/grouping/query_ball_point.cu#L93

However, you use it as an array.

https://github.com/liruihui/PU-GAN/blob/c7add7bbe32991d316375e8aba65e1f87a545763/tf_ops/grouping/query_ball_point.cu#L37

It should change to:

```
if (d<*radius) {
```

_Originally posted by @hzxie in https://github.com/liruihui/PU-GAN/issues/15#issuecomment-569261634_

As mentioned above, please double-check the grammar errors in the source code.
Thank you!

**Comment by liruihui** [comment]
It is inherited from another repository. I did not carefully check. Thanks for your suggestion. 

Ruihui Li
