### ISSUE TITLE
evaluate.py

### ISSUE THREAD

**Issue by 964918993** [liruihui/PU-GAN#17]
Hi, I have a problem with the python file (evaluate.py).

When I tried to run it by the command (python evaluate.py --pred data/test/output/fandisk.xyz --gt data/test/fandisk.xyz), it did not work and had an error(AttributeError: 'Namespace' object has no attribute 'name').
Was I use the wrong command or take the wrong step to run the py file? Do you have any idea about my problem?
Thanks!

**Comment by liruihui** [comment]
The parameter "pred" and "gt" represent the corresponding folder. :)

Ruihui Li

**Comment by 964918993** [comment]
Sorry, I don't quite understand. Can you tell me in detail? I delete the file name and input (py python --pred data/test/output --gt data/test). I tried again just now, but it's still useless.What conmand should I input to run the py file?
Thanks!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Li Ruihui"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月2日(星期四) 下午4:54
收件人:&nbsp;"liruihui/PU-GAN"<PU-GAN@noreply.github.com&gt;;
抄送:&nbsp;"VAMPIRE--。"<964918993@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liruihui/PU-GAN] evaluate.py (#17)




The parameter "pred" and "gt" represent the corresponding folder. :)
 
Ruihui Li

**Comment by liruihui** [comment]
![image](https://user-images.githubusercontent.com/31917103/71661666-ec830380-2d89-11ea-9f0b-9cb4cd044c64.png)
"pred" and "gt" folder contains the corresponding predicted points and gt points with the same names.

Actually, it is modified from [evaluate.py](https://github.com/yifita/3PU/blob/master/code/evaluate.py)

Ruihui Li

**Comment by aniqueakhtar** [comment]
If you comment out this line:
`NAME = FLAGS.name`
The error should go away.

**Comment by dongxiansheng123** [comment]
> Hi, I have a problem with the python file (evaluate.py).
> 
> When I tried to run it by the command (python evaluate.py --pred data/test/output/fandisk.xyz --gt data/test/fandisk.xyz), it did not work and had an error(AttributeError: 'Namespace' object has no attribute 'name').
> Was I use the wrong command or take the wrong step to run the py file? Do you have any idea about my problem?
> Thanks!
Hello, friend. Can we add friends to exchange this question. My qq is 747457132

**Comment by jeycechen** [comment]
> 4,hey,bro, have you solve it? could you give me some helpful suggestion ? i meet the same problem with you :) ,thanks a lot !
