### ISSUE TITLE
how to solve the problem 

### ISSUE THREAD

**Issue by xiaoxiaobozb** [liruihui/PU-GAN#20]
importerror:  /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found
(i dont have to the authority system)

**Comment by truebelief** [comment]
I think you need to:
`sudo apt-get upgrade libstdc++6`
And then change `-D_GLIBCXX_USE_CXX11_ABI=1` to `-D_GLIBCXX_USE_CXX11_ABI=0`.
