### ISSUE TITLE
Efficiency issue of evaluation_code and prepare_data

### ISSUE THREAD

**Issue by hzykent** [liruihui/PU-GAN#21]
Thank you for sharing your excellent work.

I tried to compile the code in the folder of evaluation_code and the folder of prepare_data (PU-Net). Both are successfully compiled and tested. However, I found that these programs are extremely slow. Considering the relatively large dataset, it takes days to preprocess the data and to calculate the evaluation metrics. 

Is it also an issue for you or I'm simply made something wrong?

Hope to get back from you soon~

**Comment by liruihui** [comment]
If possible, pls install the CGAL library using release mode, which may make the whole process faster.
But roughly, it is still slow for large mesh.
