### ISSUE TITLE
how to change the up_ratio?

### ISSUE THREAD

**Issue by riitoku** [liruihui/PU-GAN#22]
Hi, appreciate your excellent work.

I used the pretrained model and tried to change `up_ratio` to another value (1 or 2 etc.) by following command:
`python pu_gan.py --phase test --up_ratio 2`
but did not run successfully, the following error is displayed:
`InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1,4,128,256] rhs shape= [1,6,128,256]
	 [[node save/Assign_39 (defined at /home/yaolye/model/PU-GAN-master/Upsampling/model.py:257) ]]`

I also tried to retrain the model, but it seems that it can only run successfully when `up_ratio` is 4.

Could you tell me how to solve this problem?

Looking forward to your reply

**Comment by liruihui** [comment]
It needs to train separated models with different up-ratios. 
The default setting is 4 in our released model, which is only feasible for the r=4.
