### ISSUE TITLE
knn_point_2 function in get_edge_feature

### ISSUE THREAD

**Issue by ghost** [liruihui/PU-GAN#23]
Why is there a concatenation between `batch_indices` and `point_indices`?
I am confused with the `batch_indices`, which looks having no impact on the later `tf.gather_nd` operation.

**Comment by liruihui** [comment]
The code is inherited from [MPU](https://github.com/yifita/3PU/blob/master/code/tf_ops/grouping/tf_grouping.py). 
You may check.
