### ISSUE TITLE
LiDar data

### ISSUE THREAD

**Issue by Li-QY** [liruihui/PU-GAN#24]
Hello, I have a question about the LiDar data part. Regarding the segmentation of large point clouds files, did you crop the LiDar data into blocks in space like PointNet segmentation or divide it into sectors according to angle ?

**Comment by AngZhai** [comment]
Hi, Have you solved the problem？

**Comment by liruihui** [comment]
As shown in code, we use FPS to select many seed points and use KNN to obtain the input patch.
Then upsampling each patch and combining them together.
But for some following work, they seem to use the semantic label to crop the object and then do the upsampling, which is also reasonable.

**Comment by Nhunguts** [comment]
> As shown in code, we use FPS to select many seed points and use KNN to obtain the input patch.
> Then upsampling each patch and combining them together.
> But for some following work, they seem to use the semantic label to crop the object and then do the upsampling, which is also reasonable.

Hi @liruihui , sorry that I bother you again. Could you please show me in which part of the code does the "combining them together". I understand that we segment the original point cloud into small patches, then train with the patches. After that, if I use the model for testing, I can just test for a point cloud similar to a patch, doesn't it? So, how can I test my model with a big point cloud? Thank you so much.
