### ISSUE TITLE
the points outputs

### ISSUE THREAD

**Issue by AngZhai** [liruihui/PU-GAN#26]
thanks for your work,here is my outputs:
source:
![source](https://user-images.githubusercontent.com/44161859/89114655-a756b980-d4b1-11ea-97f1-84cf3bbdec10.png)

outputs:
![outpus](https://user-images.githubusercontent.com/44161859/89114660-b178b800-d4b1-11ea-898c-4bc148fdadf9.png)

source-1:
![source-2](https://user-images.githubusercontent.com/44161859/89114665-b9d0f300-d4b1-11ea-95d8-359bec21da72.png)

outputs-1:
![outputs-2](https://user-images.githubusercontent.com/44161859/89114673-c8b7a580-d4b1-11ea-8931-547e81b136da.png)

Why are my results so different？What's wrong with me？

**Comment by alitokur** [comment]
@AngZhai did you check the vertices number for two results?

**Comment by liruihui** [comment]
We use FPS to select many seed points and use KNN to obtain the input patch.
Then upsampling each patch and combining them together.
But for some following work, they seem to use the semantic label to crop the object and then do the upsampling, which is also reasonable.

**Comment by zeng-hello-world** [comment]
@AngZhai Hi,
Can you share me with your config for lidar point clouds generation?

**Comment by Nhunguts** [comment]
Hi @liruihui  and @AngZhai, I have a problem when testing. In training, each patch has 512 points, and it be upsampling to 2048 points. When testing, every input point cloud (even a big point cloud) will be generate to 2048 point cloud out put. Could you please help me with this? Thank you.
