### ISSUE TITLE
Any shortcut for evaluate part?

### ISSUE THREAD

**Issue by zwb0** [liruihui/PU-GAN#27]
Hi,
    Do we need to evaluate the metric by typing this command `./evaluation Icosahedron.off Icosahedron.xyz` one by one to go through all the test point clouds, then use evaluate.py? Is there any shortcut for evaluate all the output point clouds?
Thanks in advance!

**Comment by aniqueakhtar** [comment]
Same question. Would love an answer.
The documentation is also not explaining what the `evaluate.py` code is used for?

**Comment by liruihui** [comment]
> Hi,
> Do we need to evaluate the metric by typing this command `./evaluation Icosahedron.off Icosahedron.xyz` one by one to go through all the test point clouds, then use evaluate.py? Is there any shortcut for evaluate all the output point clouds?
> Thanks in advance!

You may check how to use "os.system" in python.
