### ISSUE TITLE
Model doesn't work with the test file provided in ReadMe

### ISSUE THREAD

**Issue by ModiGit** [liruihui/PU-GAN#3]
Thanks for sharing the code!  This is not a huge deal, but spent few hours figuring it out so I want others to benefit from my experience. 
By default, the code loads the saved model based on the latest checkpoint in the log file using this function in Common/model_utils.py:
ckpt = tf.train.get_checkpoint_state(checkpoint_dir)
This function needs the checkpoint file which is generated by tensorflow while saving models. Since the model provided for testing in [here](https://drive.google.com/open?id=12kWoB0-_tflq65RNpJEnNGTTwPXa6IOH) doesn't have the checkpoint file, tensorflow won't be able to load the model. The walk-around is to manually set checkpoint_path in Upsampling/model.py to model/model-100, so tensorflow loads that particular checkpoint. 
:)

**Comment by liruihui** [comment]
Thanks for your help.

Ruihui Li

**Comment by alitokur** [comment]
@ModiGit sir, it should be something like the following, right?
 checkpoint_path = "/home/alitokur/Softwares/PU-GAN/model/model-100"

**Comment by ModiGit** [comment]
> @ModiGit sir, it should be something like the following, right?
> checkpoint_path = "/home/alitokur/Softwares/PU-GAN/model/model-100"

@alitokur yes if that path is where you downloaded the model.

**Comment by phy12321** [comment]
Excuse me, from where  can I download  the checkpoint file ? It seems no ckp file in given download links.

**Comment by QWTforGithub** [comment]
Thany you for your sharing!

**Comment by QianLi-cell** [comment]
感谢您的帮助！！！
