### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by guochengqian** [liruihui/PU-GAN#5]
Hello.  Thanks for sharing the code, which makes it easy for us to follow your work.
For the evaluation code `evaluation.cpp`, we notice that you print disk indices instead of calculating the evaluation metric (uniformity). Is it possible that the `evaluation.cpp` file you provided is not the final version?
Also, there is no code for calculating CD and HD metrics, can you share the code for that?

Thank you

**Comment by liruihui** [comment]
Actually, you can find all your needs in evaluate.py.

**Comment by guochengqian** [comment]
Thank you
