### ISSUE TITLE
undefined symbol error

### ISSUE THREAD

**Issue by windspectator** [liruihui/PU-GAN#6]
I have successfully compiled all TF operators, but when I run "python pugan.py", I still got such error:`tensorflow.python.framework.errors_impl.NotFoundError: /home/ytliu/pugan/tf_ops/approxmatch/tf_approxmatch_so.so: undefined symbol: _ZN10tensorflow12OpDefBuilder5InputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

system: Ubuntu 18.04 64x
cuda: 10.1
tensorflow: 1.13.1
g++: 6.5.0
python: 3.6

By the way, I've edited content of *_compile.sh files. Below is an example(tf_approxmatch_compile.sh):
```
#!/usr/bin/env bash
#/bin/bash

/usr/local/cuda-10.1/bin/nvcc tf_approxmatch_g.cu -o tf_approxmatch_g.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC

g++ -std=c++11 tf_approxmatch.cpp tf_approxmatch_g.cu.o -o tf_approxmatch_so.so -shared -fPIC -I /home/ytliu/.conda/envs/pugan/lib/python3.6/site-packages/tensorflow/include  -I /usr/local/cuda-10.1/include -I /home/ytliu/.conda/envs/pugan/lib/python3.6/site-packages/tensorflow/include/external/nsync/public -lcudart -L /usr/local/cuda-10.1/lib64/ -L /home/ytliu/.conda/envs/pugan/lib/python3.6/site-packages/tensorflow -ltensorflow_framework -O2 -D_GLIBCXX_USE_CXX11_ABI=1
```

**Comment by windspectator** [comment]
I solved it by switching to another machine.
It seems this error is caused by multiple cuda versions on one machine which are interfering others, but I didn't encounter this before when I was compiling tf operators.

**Comment by voidrank** [comment]
@windspectator There is a good compilation template for ops from pointnet++ and other related ops.

```
CUDA_ROOT=/opt/common/cuda/cuda-10.0.130 
TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')

echo $CUDA_ROOT
echo $TF_INC
echo $TF_LIB

$CUDA_ROOT/bin/nvcc tf_approxmatch_g.cu -o tf_approxmatch_g.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC

# TF>=1.4.0
g++ -std=c++11 tf_approxmatch.cpp tf_approxmatch_g.cu.o -o tf_approxmatch_so.so -shared -fPIC -I$TF_INC/ -I$TF_INC/external/nsync/public -L$TF_LIB -ltensorflow_framework -I$CUDA_ROOT/include -lcudart -L$CUDA_ROOT/lib64/ -O2 -D_GLIBCXX_USE_CXX11_ABI=1
```

**Comment by mtli77** [comment]
> I solved it by switching to another machine.
> It seems this error is caused by multiple cuda versions on one machine which are interfering others, but I didn't encounter this before when I was compiling tf operators.

Change the `-D_GLIBCXX_USE_CXX11_ABI=1` into `-D_GLIBCXX_USE_CXX11_ABI=0` could solve this problem.
