### ISSUE TITLE
KITTI test

### ISSUE THREAD

**Issue by JieLi1994** [liruihui/PU-GAN#9]
Hi, i'm interested in kitti part. 
does your model training in 3D models and just test in kitti?
so i want know the details

**Comment by JieLi1994** [comment]
@liruihui

**Comment by liruihui** [comment]
FYI, I just test in KITTI.

**Comment by JieLi1994** [comment]
That's really interesting.  Near-dense is a feature of lidar data. Appropriate upsampling helps object detection. This may be helpful for autonomous driving. Have you tried using the upsampled lidar data for object detection? （such as KITTI）

**Comment by JieLi1994** [comment]
@liruihui

**Comment by liruihui** [comment]
not yet

**Comment by godspeed1989** [comment]
Can you specify details of the test on KITTI?
Do you upsample the whole LiDAR point cloud or just select a part of it for illustration?

**Comment by liruihui** [comment]
when we do the upsampling, we crop the data into pieces and upsample them one by one, and finally combine them together,  as the paper said.

Ruihui Li

**Comment by JieLi1994** [comment]
can you release some scipts about kitti test？I want specify the details
thanks！

**Comment by liruihui** [comment]
It is already presented in the provided scripts. No matter it is synthetic or LiDAR point, we select some seeds on it and for each seed, we crop 256 points as input to get an upsampled result.

Ruihui LI

**Comment by zeng-hello-world** [comment]
@liruihui Hi,
I want to know the details about LiDAR.
Since you split whole frame lidar point cloud into pieces then process them, how do you make sure the result of each piece of point cloud's boundary can match its neighbors?

Thanks!
